[package]
name = "dlyblink"
version = "0.1.0"
authors = ["John Jorgensen <john@2gn.com>"]

[dependencies]
arduino = "0.1"
avr_delay = { git = "https://github.com/pusherofbrooms/avr-delay" }
# avr_delay = { path = "../avr-delay" }